version: 2
updates:
  - package-ecosystem: npm
    directory: /B2CBuildAllPolicies/B2CBuildAllPoliciesV1
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: B2CUploadAllPolicies/B2CUploadAllPoliciesV1
    schedule:
      interval: weekly
